# Generated by Django 6.0.4 on 2026-05-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('saudacao', 'Saudação'), ('sobrecarga', 'Sobrecarga'), ('tarefas', 'Organização de tarefas'), ('comunicacao', 'Comunicação'), ('emocional', 'Apoio emocional')], max_length=50)),
                ('gatilho', models.CharField(max_length=200)),
                ('resposta', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_usuario', models.TextField()),
                ('resposta_sistema', models.TextField()),
                ('modo', models.CharField(choices=[('simples', 'Conversa simples'), ('sobrecarga', 'Estou sobrecarregado'), ('tarefas', 'Organizar tarefa')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
