# Generated by Django 6.0.4 on 2026-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_usuario', models.TextField()),
                ('resposta_sistema', models.TextField()),
                ('modo', models.CharField(choices=[('simples', 'Conversa simples'), ('sobrecarga', 'Estou sobrecarregado'), ('tarefas', 'Organizar tarefa')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
