# Generated by Django 6.0.4 on 2026-05-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistente_tea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('saudacao', 'Saudação'), ('sobrecarga', 'Sobrecarga'), ('tarefas', 'Organização de tarefas'), ('comunicacao', 'Comunicação'), ('emocional', 'Apoio emocional')], max_length=50)),
                ('gatilho', models.CharField(max_length=200)),
                ('resposta', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
