# Generated by Django 6.0.4 on 2026-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistente_tea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
